### PR TITLE
Run tests from src rather than dist

### PR DESCRIPTION
**Pull request by Otto-AA**

### CODE REVIEW

**Comment by jeff-zucker** [comment]
Any idea why switching from dist to src dropped SolidFileClient.js coverage from 84% to 21%?

Also, is there any way to get the coverage to not display some of the extraneous stuff like the externals?

**Comment by jeff-zucker** [comment]
Nevermind about the coverage thing - I had to change jest.config.js and session.test.js - the first was ignoring src and the second was using it so 20% was what session  covers.  With the  fix to jest.config.js, it's back to 80%+

**Comment by Otto-AA** [comment]
Oh, that's likely because of the session test.

You should be able to remove the coveragePathIgnorePatterns now, because node_modules is the default anyway. If you want you can set `collectCoverageFrom: [ "./src/**" ]` to be exact on what we want to be included, but it shouldn't make a difference for now.

**Comment by jeff-zucker** [comment]
On mock, I may have a different solution (in the long run) - if solid-rest and its descendants respond to login requests with mock data, we can test against logging in to file:// or app:// and that way, only the base URL needs to be changed to run the test as real against a pod or mock against solid-rest mini-pod.

**Comment by jeff-zucker** [comment]
Because, obviously, we should run all tests against a real pod manually before release.

BTW are you still experiencing things that might be broken in solid-auth-cli/solid-rest-file?

**Comment by Otto-AA** [comment]
> BTW are you still experiencing things that might be broken in solid-auth-cli/solid-rest-file?

Not really. I will add tests for the SolidApi which will use solid-auth-cli so I will probably encounter unexpected behavior. But I think that the tests for the core methods (fetch, get, head, ...) should already cover that and that copy and others won't notice any more errors in solid-auth-cli.

**Pull request merged**
