### PR TITLE
Set SolidApi.fetch to throw and added new tests

### PR DESCRIPTION
**Pull request by Otto-AA**
* to be consistent fetch now throws if response.ok is set to false
    I've updated methods in SolidFileClient to use get and handle thrown errors
  * added some tests for SolidApi
  * added tests for apiUtils 

In the tests I've encountered something unexpected regarding the post method: If I try to create a folder which already exists with post it responds with 409 instead of creating a new one. And trying to overwrite a file resolves with 201 but I don't see a new one being created. Is this something related to solid-auth-cli?

### CODE REVIEW

**Comment by jeff-zucker** [comment]
It looks like your changes to SolidFileClient are on a version many commits ago.  I do not know what the impact of these will be if I merge.  Please separate out the commits so that one PR is for changes to your packages and if you have changes for SolidFileClient put those in a PR of their own after doing a pull of my most recent commits.

**Comment by jeff-zucker** [comment]
I'll look into the file:// problems.  You can always switch to using remote files to see if this is a problem in solid-rest-file.

**Comment by jeff-zucker** [comment]
I guess I'll just backup and merge and assume that the changes you made to SolidFileClient will not clobber things I've done since.

**Comment by Otto-AA** [comment]
I didn't notice that I was behind on my local branch, so I've merged your changes into mine afterwards via github (see https://github.com/jeff-zucker/solid-file-client/pull/50/commits/86a685f4d4009cd59d0b220bd249eef0e82d926f). While this only was a little change to do, it also added your changes so that's why many things seem duplicated. I'll try to check and git pull from now on before commiting.

**Comment by jeff-zucker** [comment]
Not a problem, I merged any everything looked good.

**Pull request merged**
