### PR TITLE
Fix environment variables for tests in windows

### PR DESCRIPTION
**Pull request by Otto-AA**
It looks like windows doesn't support setting environment variables like `TEST_PREFIX=https:// jest`, that's why the travis build completely failed previously. I've changed it so travis sets the environment variables and the tests for windows actually run.

As noted by @CxRes , it looks like the test for windows fails for `tests/SolidApi.links.test.js` with the prefix `file://`. I haven't looked much into this issue, but I will my initial findings on these errors to #130 .

### CODE REVIEW

**Comment by Otto-AA** [comment]
(Don't merge yet, still need to check something in travis. Doesn't look like it should...)

**Comment by Otto-AA** [comment]
Nevermind, the travis setup looks good now. The test setup is just buggy for windows.

**Comment by CxRes** [comment]
May i suggest that you install "cross-env" for global variables. or if you like I could set it up and push it in a day or so?

**Comment by Otto-AA** [comment]
Thanks for that suggestion, it looks like a good idea. I will add it and update this PR in a few minutes.

On travis I would still use the env option, because it makes it easier to view the different builds in different environments. So I will leave that for now

**Pull request merged**
