### PR TITLE
Update a few recursive tests

### PR DESCRIPTION
**Pull request by Otto-AA**
I've updated some recursive tests (copy and delete). They rely on the PR I've made in solid-rest so with the current solid-rest versions these tests will fail for now. With the new one all pass.

### CODE REVIEW

**Comment by jeff-zucker** [comment]
Very cool, great work, thanks.  Looking forward to the PR on solid-rest.

**Comment by Otto-AA** [comment]
Have you already taken a look at the PR on solid-rest? (https://github.com/jeff-zucker/solid-rest/pull/3)

**Comment by jeff-zucker** [comment]
Ah, no, I hadn't received any notification of it.  Need to change github
settings I guess.  I'll look now.

**Comment by jeff-zucker** [comment]
I had already started fixing the localStorage container issues, but thanks
for beating me to it.

**Comment by Otto-AA** [comment]
Oh weird, I've thought github automatically sets the notification settings to watching on own repositories. Can you ping me when solid-file-client uses the new version of solid-rest?

**Comment by jeff-zucker** [comment]
Will do, trying to debug the 5.x file creation thing ATM.

**Pull request merged**
