### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Otto-AA**
I've updated jsdoc documentation and fixed linting errors. I've also added several TBDs

@jeff-zucker I've added several TBD comments, where I think something should be changed, or where I need help on the types for JSDoc. They are just things that I noticed, so feel free to disagree and comment on them if you have a different opinion. You could either start a review in this PR to tell me your thoughts, or just write github comments somewhere. Whatever you prefer :)

### CODE REVIEW

**Comment by Otto-AA** [comment]
By the way, I think we should move several methods used by readFolder to folderUtils.js. The SolidApi class is already huge enough, so splitting this seems reasonable to me.

**Comment by jeff-zucker** [comment]
I have no problem with moving things from SolidApi to utils as you see fit.

**Comment by jeff-zucker** [comment]
Your suggestions generally look good.  I'll merge and then examine them one
by one.

**Comment by jeff-zucker** [comment]
@Otto-AA , you asked why in rdf-query I set this.store rather than just returning store and why I query an empty source.  This allows us to reuse a source file with a new query without re-loading the source.  So if we send query1 to url1, that stores the loaded file in this.store.  Later, when we do query2 without a source, the query uses this.store from the previous run without re-loading it.  I'm not sure we actually use that feature currently but it seems useful enough that I see no reason to remove it.

**Comment by jeff-zucker** [comment]
I've now documented the above in the code.

**Pull request merged**
