### PR TITLE
add comment. start exploration in this file.

### PR DESCRIPTION
**Pull request by ewingson**
d2021-01-23 t21:59

### CODE REVIEW

**Comment by jeff-zucker** [comment]
@ewingson please work in any way that is comfortable for you.  Comments are good.  We can always clean up later.  If you need my review or have questions, please ping me in chat.

**Comment by ewingson** [comment]
I'm forever thankful that finally, after all this observation, I get the opportunity to get my hands dirty. ;-)

**Comment by ewingson** [comment]
the CDN has its scope in all the files of the app, hasn't it ?
I work for the beginning with ctrl-c/ctrl-v from the example.
and the philosophy of submitting little and often, is that okay ?

**Comment by ewingson** [comment]
@jeff-zucker 
(I put it under the old PR cause my github branch has no issues offered by github)
could you please review https://github.com/ewingson/solid-file-client/tree/use_dpop_auth/docs/examples/advanced (both files)

several q's opened

1. are the dependencies all needed ?
2. are they in the right order ?
3. is it correct to call the actual code at the very bottom ?
4. `session` is used in `index` L77 and L103. does that matter ? 
5. another duplicate `getDefaultSession` in `index` L77 and copy.js L2 ?

statements
I wanna trace the option buttons / checkboxes / ids / classes.
I wanna use existing code wherever possible.

to really work it / control it ... I must `understand` it.
what do you think ?

**Pull request closed without merging**
